# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "rest-client"
gem "htmlentities"
gem "colorize"
gem "terminal-table"
gem "artii"
gem "rmagick", "~>2.16.0"
gem "word_wrap"
gem "catpix"
gem "require_all"
